openapi: 3.0.1
info:
  title: monster-abishai-blue
  x-cortex-tag: monster-abishai-blue
  x-cortex-custom-metadata:
    alignment: lawful-evil
    type: fiend
    challenge_rating: 9
    legendary: true
    source: dnd-5e
  x-cortex-type: monster
